# Generated by Django 4.2 on 2023-04-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travela_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='pendingUsers',
            field=models.ManyToManyField(blank=True, related_name='pending_users', to='travela_api.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='pendingRequests',
            field=models.ManyToManyField(blank=True, to='travela_api.trip'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='sharedUsers',
            field=models.ManyToManyField(blank=True, related_name='shared_users', to='travela_api.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='userImages/'),
        ),
    ]
