# Generated by Django 4.2 on 2023-05-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travela_api', '0004_user_useremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userID',
        ),
        migrations.AlterField(
            model_name='user',
            name='userEmail',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
