# Generated by Django 4.2 on 2023-05-01 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travela_api', '0005_remove_user_userid_alter_user_useremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='acceptedRequests',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pendingRequests',
        ),
    ]
