# Generated by Django 3.2.18 on 2023-05-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travela_api', '0009_alter_itineraryentry_location_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinationName', models.CharField(max_length=50)),
                ('destinationTag', models.CharField(max_length=50)),
                ('destinationImage', models.CharField(max_length=50)),
                ('destinationLocation', models.CharField(max_length=50)),
            ],
        ),
    ]
