# Generated by Django 3.2.18 on 2023-05-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travela_api', '0010_homedestination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homedestination',
            name='destinationImage',
            field=models.CharField(max_length=200),
        ),
    ]
