# Generated by Django 4.2 on 2023-05-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travela_api', '0011_alter_homedestination_destinationimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryentry',
            name='dateTime',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='itineraryentry',
            name='description',
            field=models.CharField(max_length=800),
        ),
    ]
